### ISSUE TITLE
Cannons plugin damage tracking

### ISSUE THREAD

**Issue by galacticwarrior9** [TylerS1066/Movecraft-Combat#38]
Movecraft has built-in integration for the [Cannons](https://dev.bukkit.org/projects/cannons) plugin. On my server, cannons from this plugin are the primary armaments of most ships. If possible, it would be great to see some sort of damage-tracking implemented for it!

**Comment by TylerS1066** [comment]
To try and streamline the updating of MCC I would prefer to keep external dependencies as small as possible (infact, I plan on removing WG support from both this and Movecraft itself eventually and instead use addons such that a multitude of protection plugins can be supported with the same core Movecraft and MCC plugins).

This does bring up a good point of adding an API to support external plugin damage types, and I will update the DamageManager and DamageType classes to support custom plugin damage types.  I will most likely use the Cannons plugin to develop a test addon to MCC, but I do not plan on thoroughly testing it for production servers or releasing it officially.

**Comment by TylerS1066** [comment]
I've done the necessary updates to the internals of Movecraft-Combat.  In addition, I've created the [Movecraft-Cannons](https://github.com/TylerS1066/Movecraft-Cannons) repo to house the addon.

Eventually I'll move all of the Cannons dependency out of Movecraft itself, but for now I am going to focus on extending Movecraft-Combat with the Cannons plugin.

**Comment by TylerS1066** [comment]
@galacticwarrior9 Movecraft-Cannons v0.1.0 has been released: https://github.com/TylerS1066/Movecraft-Cannons/releases/tag/v0.1.0

If you can, please download the snapshot of MCC from the link provided there and Movecraft-Cannons and test it out!
