### ISSUE TITLE
Harvest block flag

### ISSUE THREAD

**Issue by Pvprod34** [TylerS1066/Movecraft-Combat#40]
I was wondering if you could add a way of disabling harvest blocks in certain WG regions. This would allow for setup protected areas to be safe from crafts that have ram type weapons.

**Comment by TylerS1066** [comment]
Movecraft-Combat does not include harvest blocks.  That would be part of Movecraft ([APDevTeam for 1.10-1.12](https://github.com/APDevTeam/Movecraft) or [Eirik's fork for 1.13+](https://github.com/eirikh1996/Movecraft))
