### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by Pvprod34** [TylerS1066/Movecraft-Combat#42]
https://imgur.com/a/FwKmIMk
Getting this spam in my console after using my tnt cannons (wasn't piloted or using directors or anything.

**Comment by TylerS1066** [comment]
This looks like an incompatible version of movecraft.  I'd recommend grabbing [this beta build](https://github.com/APDevTeam/Movecraft/suites/1689105272/artifacts/31682444) of APDevTeam movecraft.

**Comment by Pvprod34** [comment]
> This looks like an incompatible version of movecraft. I'd recommend grabbing [this beta build](https://github.com/APDevTeam/Movecraft/suites/1689105272/artifacts/31682444) of APDevTeam movecraft.

thanks tyler its fixed!
I was wondering if you was planning on working on that repair module you spoke of a few months back still.

**Comment by TylerS1066** [comment]
> I was wondering if you was planning on working on that repair module you spoke of a few months back still.

My current focus is to polish off Movecraft-Combat and then finish Movecraft-Warfare.  Once those two are completed, I'll move onto Movecraft-Repair.
