### ISSUE TITLE
Same-tick problem

### ISSUE THREAD

**Issue by TylerS1066** [TylerS1066/Movecraft-Combat#55]
![2021-04-01_20 44 29](https://user-images.githubusercontent.com/7319776/113371106-192a2000-932b-11eb-9a8f-88612cd8b282.png)

As shown here, when TNT is dispensed in the same tick as the piston extends, it fails, but a minor delay fixes problems.

EDIT: to add the delay replace the far redstone with a repeater

**Comment by drfiveminusmint** [comment]
I believe this may be caused by MovecraftCombat's custom dispenser event being processed after the piston event. I am unsure how to fix this, however.

**Comment by TylerS1066** [comment]
As an update to this, I was able to do some debugging and discover that yes, dispenses are handled after pistons in 1.12.2 spigot.

**Comment by TylerS1066** [comment]
While the original issue is not solved, a recent commit to `legacy` has fixed some guns which would explode.
