### ISSUE TITLE
TNT alignment on translocation

### ISSUE THREAD

**Issue by HalfQuark** [TylerS1066/Movecraft-Combat#59]
The current translocation fix tp's every translocated TNT to the same coordinates and removes the small spread created by the random velocity upon dispensing. This causes translocation guns to deal noticeably less damage in comparison to non-translocation guns and 1.10 translocation guns.

**Comment by TylerS1066** [comment]
This was fixed somewhere in https://github.com/TylerS1066/Movecraft-Combat/commit/8b446087d7f6c29a764445902346a53762595bcb https://github.com/TylerS1066/Movecraft-Combat/commit/43356b2e8a2cafd3cbb0aff0aab72816d5c2d7a1 or https://github.com/TylerS1066/Movecraft-Combat/commit/e0c9b5109a5a7239dbcbc43d7852bde8d4636aff
