### ISSUE TITLE
Block translocation

### ISSUE THREAD

**Issue by HalfQuark** [TylerS1066/Movecraft-Combat#62]
![2021-04-09_16 53 33](https://user-images.githubusercontent.com/64480337/114207586-6f631880-9954-11eb-8e54-a07351c5ea16.png)
Translocation when the TNT is inside a moved block does not work and the above setup demonstrates a common case in some translocation guns. When extended the TNT entity will stay inside of the block instead of moving 1 extra block which doesn't correspond to 1.10 behaviour and will break some guns.

**Comment by TylerS1066** [comment]
This was discussed by the dev and admin teams when we were deciding to bring TNT translocation into 1.11+ and decided to not bring this (and the complexity/undefined behavior of slime and honey translocation).
