### ISSUE TITLE
Partial translocation

### ISSUE THREAD

**Issue by HalfQuark** [TylerS1066/Movecraft-Combat#63]
![2021-04-09_16 58 39](https://user-images.githubusercontent.com/64480337/114207984-e00a3500-9954-11eb-9f6b-9af0b8bbe939.png)
This setup should translocate the TNT one block and let it fall through the hole. Instead it doesn't translocate the TNT at all which doesn't correspond to 1.10 behaviour and may possibly break some side guns.

**Comment by TylerS1066** [comment]
This is such a small edge case which is unused that we will not be making our code more complex by fixing it.
