### ISSUE TITLE
Incorrect TNT item removal on dispense event

### ISSUE THREAD

**Issue by HalfQuark** [TylerS1066/Movecraft-Combat#69]
1. When there's only 1 TNT item in a dispenser inventory it is not removed and no TNT is spawned.
2. When there's a stack of TNT with 1 item only and other stacks of TNT in a dispenser inventory TNT will be spawned but no TNT will be consumed where the 1 TNT stack will be transferred to another TNT stack.

**Comment by TylerS1066** [comment]
Please only report a single issue per github issue unless they are due to the same core problem.
