### ISSUE TITLE
Ship bounties

### ISSUE THREAD

**Issue by TylerS1066** [TylerS1066/Movecraft-Combat#7]
Allow players to put bounties on the sinking of another player, similar to ingame kill bounties.

Split profits along a certain config-able percentage of kill vs assists.

**Comment by Pulverizer** [comment]
Split earning by damage % delt? This would be both fair and dissuade players from kill stealing.

**Comment by TylerS1066** [comment]
Unfortunately I don't plan on tracking the number of blocks damaged so as to reduce the cpu and memory impact of this plugin.

My current plan was to allow you to set a configurable percent that goes to the last person to damage, and the rest would get evenly split between the others, or you could set the percent to -1 to enable even spread across all players who caused damage.

**Comment by HumorousFool** [comment]
This would require a Vault softdepend. Is that ok or is this best suited for yet another addon in this Movecraft jungle?

**Comment by TylerS1066** [comment]
> This would require a Vault softdepend. Is that ok or is this best suited for yet another addon in this Movecraft jungle?

Correct, that is why I labelled it as an "addon".

**Comment by TylerS1066** [comment]
This and #4 are both outside the already large scope of this plugin.  We may still look into developing this but it will need to be in an addon to Movecraft-Combat.
