### ISSUE TITLE
Incorrect TNT dispensing when only 1 TNT item is present

### ISSUE THREAD

**Issue by HalfQuark** [TylerS1066/Movecraft-Combat#72]
When there's only 1 TNT item in a dispenser inventory it is not removed and no TNT is spawned.

**Comment by TylerS1066** [comment]
This was fixed as of 419edd4faad136bee1fd112c0b5cca900d90296e

**Comment by TylerS1066** [comment]
Fixed in main as of c69a52bbea362d71811c395ac9b3a193fc06ec8d
