### ISSUE TITLE
Incorrect TNT item removal on TNT dispense with a specific dispenser inventory

### ISSUE THREAD

**Issue by HalfQuark** [TylerS1066/Movecraft-Combat#73]
When there's a stack of TNT with 1 item only and other stacks of TNT in a dispenser inventory TNT will be spawned but no TNT will be consumed where the 1 TNT stack will be transferred to another TNT stack.

**Comment by TylerS1066** [comment]
This was fixed in legacy as of 419edd4faad136bee1fd112c0b5cca900d90296e

**Comment by TylerS1066** [comment]
Fixed in main as of c69a52bbea362d71811c395ac9b3a193fc06ec8d
