### ISSUE TITLE
Cannon Directors don't direct when not looking at a block

### ISSUE THREAD

**Issue by goodroach** [TylerS1066/Movecraft-Combat#83]
Version: 1.16.5
MCC version: Alpha 3 (iirc most recent one)
**What doesn't work:**
The cannon director doesn't direct the shots when you look at an empty space or the block you are looking at is beyond the CannonDirectorRange amount. From what I can guess, it could be the code for the gun to shoot at the general direction isn't activated correctly. 
**What should happen:**
The cannon director should direct the TNT cannon shots regardless of if you are pointing at a block or not.

**Comment by TylerS1066** [comment]
I suspect this has to do with the fact that https://github.com/TylerS1066/Movecraft-Combat/pull/71 was merged to legacy shortly after the split for the 8.0 alpha builds.  Let me generate a test build with that PR merged in and see if that solves the issue for you.  If it does, I'll include it in the next alpha of Combat.

**Comment by TylerS1066** [comment]
Scratch that, it appears that #71 was brought in on this commit: https://github.com/TylerS1066/Movecraft-Combat/commit/5413451fb12f0db748aa223c9f38a654418a4fd2.  @drfiveminusmint you seem to know the director code the best, could it be that the target block is not reporting back properly for a newer MC version compared to the 1.12.2 you developed this solution against?

**Comment by drfiveminusmint** [comment]
I have no idea why that would be the case but i'll look into it

**Comment by drfiveminusmint** [comment]
I cannot reproduce this bug on 1.17.1 paper, will test on 1.16.5 later

**Comment by goodroach** [comment]
I probably have configured my movecraft wrong again, but I'm not sure what in the config could cause such a bug.

**Comment by goodroach** [comment]
Oops, I wasted your guy's time turns out I set Air as a transparent block. My apologies.
