### ISSUE TITLE
Transparent blocks not functioning properly. 

### ISSUE THREAD

**Issue by goodroach** [TylerS1066/Movecraft-Combat#87]
Transparent blocks is ignored for cannons being directed as they can direct through anything while AA directors direct to anything, including air blocks. I even cleared the transparent blocks list to confirm that was the case, and sure enough it was. I suspect that MCC is somehow ignoring transparent blocks. If this was already fixed in the latest dev builds please close this issue. 

**Version:**
Minecraft 1.16.5
Java 16
Movecraft Combat alpha 5

**Comment by TylerS1066** [comment]
Confirmed fixed on my 1.14.4 paper test server.
