### ISSUE TITLE
Damage to piloted ships only

### ISSUE THREAD

**Issue by goodroach** [TylerS1066/Movecraft-Combat#99]
Suggestion: Add a feature (toggleable in the config) that makes it so only piloted crafts take damage from TNT, explosions, and fire. This will also ignore worldguard regions if they have a specific flag (could be added in Movecraft-Worldguard). I'm not sure about the implementation but I was told it wouldn't be too hard if I integrated it into MCC.

**Comment by TylerS1066** [comment]
This likely would make more sense for Movecraft-WorldGuard, so I'm gonna transfer it to there.  Movecraft-Combat doesn't really give us anything extra here, and it'd likely work best to make this a set of WorldGuard flags such that owners can use it as they want.
